# Table 1 Generation for Emory and Grady data

In [1]:
import numpy as np
import pandas as pd
from tableone import TableOne

# Emory data process

In [ ]:
df_transf0 = pd.read_csv("DATA_RESULTS/df_RBCT_extractedFeat_NoImputated_tau9_v3.csv")
df_transf0.drop(['Unnamed: 0.2', 'Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
# df_transf0

'''

Eliminated the patients having pre-transfusion SF, Hb, SpO2, PF missing

'''
print(df_transf0[['med_spo2_beforeT', 'med_Hb_beforeT', 'med_SF_beforeT','med_PF_beforeT']].isnull().all(axis=1).sum())

df_transf = df_transf0[~df_transf0[['med_spo2_beforeT', 'med_Hb_beforeT', 'med_SF_beforeT','med_PF_beforeT']].isnull().all(axis=1)]
df_transf.reset_index(drop=True, inplace=True)
print(df_transf.shape)

print(len(df_transf0.pat_id.unique()), len(df_transf0.csn.unique()), len(df_transf.pat_id.unique()), len(df_transf.csn.unique()))
df_transf

In [ ]:
### LOAD EMORY TRANSFUSION PHENOTYPING DATA
AllSuperTable_0 = pd.read_csv('../Transfusion_Phenotyping_Data_EmoryGrady/df_RBC_T_AllFeatures_NoOurlierRejected_NoImputed_v1g.csv')
AllSuperTable_0

In [5]:
df_transf.columns, AllSuperTable_0.columns, df_transf['Hb'].isnull().sum(), AllSuperTable_0['SOFA_max_hourly_total'].isnull().sum()

(Index(['pat_id', 'PAT_ID', 'csn', 'encntr_id', 'dispense_dt_tm',
        'estimated_transfusion_dt_tm', 'product_cd_disp', 'bed_location_start',
        'bed_location_end', 'product_cat_cd_disp', 'orig_volume', 'year',
        'hospital_service', 'Arb', 'Tcount_7d', 'discharge_to', 'age', 'gender',
        'race', 'ethnicity', 'Hb', 'med_spo2_beforeT', 'med_Hb_beforeT',
        'med_SF_beforeT', 'med_PF_beforeT', 'MSPO2_afterT1', 'MSPO2_afterT2',
        'MSPO2_afterT3', 'MHB_afterT1', 'MHB_afterT2', 'MHB_afterT3',
        'MSF_afterT1', 'MSF_afterT2', 'MSF_afterT3', 'MPF_afterT1',
        'MPF_afterT2', 'MPF_afterT3', 'del_SPO2_1', 'del_SPO2_2', 'del_SPO2_3',
        'del_Hb_1', 'del_Hb_2', 'del_Hb_3', 'del_SF_1', 'del_SF_2', 'del_SF_3',
        'del_PF_1', 'del_PF_2', 'del_PF_3'],
       dtype='object'),
 Index(['Unnamed: 0', 'pat_id', 'PAT_ID', 'csn', 'encntr_id', 'dispense_dt_tm',
        'estimated_transfusion_dt_tm', 'product_cd_disp', 'bed_location_start',
        'bed_location_end', 'product_cat_cd_disp', 'orig_volume', 'year',
        'hospital_service', 'arbitrary', 'Arb', 'Tcount_7d', 'discharge_to',
        'age', 'gender', 'race', 'ethnicity', 'temperature', 'daily_weight_kg',
        'height_cm', 'sbp_line', 'dbp_line', 'map_line', 'sbp_cuff', 'dbp_cuff',
        'map_cuff', 'pulse', 'unassisted_resp_rate', 'spo2', 'end_tidal_co2',
        'o2_flow_rate', 'base_excess', 'bicarb_(hco3)',
        'blood_urea_nitrogen_(bun)', 'calcium', 'calcium_ionized', 'chloride',
        'creatinine', 'glucose', 'magnesium', 'osmolarity', 'phosphorus',
        'potassium', 'sodium', 'hematocrit', 'hemoglobin', 'met_hgb',
        'platelets', 'white_blood_cell_count', 'carboxy_hgb',
        'alanine_aminotransferase_(alt)', 'albumin', 'alkaline_phosphatase',
        'ammonia', 'aspartate_aminotransferase_(ast)', 'bilirubin_direct',
        'bilirubin_total', 'fibrinogen', 'inr', 'lactate_dehydrogenase',
        'lactic_acid', 'partial_prothrombin_time_(ptt)', 'prealbumin',
        'protein', 'amylase', 'lipase', 'b-type_natriuretic_peptide_(bnp)',
        'troponin', 'fio2', 'partial_pressure_of_carbon_dioxide_(paco2)',
        'partial_pressure_of_oxygen_(pao2)', 'ph',
        'saturation_of_oxygen_(sao2)', 'd_dimer', 'hemoglobin_a1c',
        'parathyroid_level', 'crp_high_sens', 'procalcitonin',
        'erythrocyte_sedimentation_rate_(esr)', 'gcs_verbal_score',
        'gcs_motor_score', 'gcs_total_score', 'vent_status', 'best_map',
        'pf_sp', 'pf_pa', 'SOFA_max_hourly_total', 'c_diff_Negative'],
       dtype='object'),
 2271,
 0)

In [ ]:
AllSuperTable_1 = df_transf.merge(AllSuperTable_0, how='left', on=['pat_id', 'PAT_ID', 'csn', 'encntr_id', 'dispense_dt_tm',
        'estimated_transfusion_dt_tm', 'product_cd_disp', 'bed_location_start',
        'bed_location_end', 'product_cat_cd_disp', 'orig_volume', 'year',
        'hospital_service', 'Arb', 'Tcount_7d', 'discharge_to', 'age', 'gender',
        'race', 'ethnicity'])
print(AllSuperTable_1['SOFA_max_hourly_total'].isnull().sum())
AllSuperTable_1

In [7]:
AllSuperTable_2 = AllSuperTable_1[~AllSuperTable_1['med_SF_beforeT'].isnull()]
AllSuperTable_2.reset_index(drop=True, inplace=True)

bsf = AllSuperTable_2['med_SF_beforeT']
cond1 = (bsf>0) & (bsf<=143)
cond2 = (bsf>143) & (bsf<=235)
cond3 = (bsf>235) & (bsf<=315)
cond4 = (bsf>315) 

C1 = pd.Series(cond1, dtype=int)*1
C2 = pd.Series(cond2, dtype=int)*2
C3 = pd.Series(cond3, dtype=int)*3
C4 = pd.Series(cond4, dtype=int)*4
AllSuperTable_2['BSF_group'] = C1 + C2 + C3 + C4

/var/folders/fl/fpg3wpyx2kl9_skm4xg51z3h0000gn/T/ipykernel_30494/2126047341.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AllSuperTable_2['BSF_group'] = C1 + C2 + C3 + C4

In [8]:
AllSuperTable_2.race.unique(), AllSuperTable_2.ethnicity.unique(), AllSuperTable_2['BSF_group'].unique()

(array(['African American  or Black', 'Caucasian or White',
        'American Indian or Alaskan Native',
        'Unknown, Unavailable or Unreported', 'Asian', 'Multiple',
        'Native Hawaiian or Other Pacific Islander'], dtype=object),
 array(['Non-Hispanic or Latino', 'Unreported, Unknown, Unavailable',
        'Not Recorded', 'Non-Hispanic~Unknown', 'Hispanic or Latino',
        'Unknown~Non-Hispanic', 'Unknown~Hispanic', 'CD:1641210453',
        'CD:1565395161', 'CD:1902530759'], dtype=object),
 array([4, 3, 2, 1]))

In [9]:
AllSuperTable_2.reset_index(drop=True, inplace=True)
race_others_i = AllSuperTable_2[~AllSuperTable_2.race.isin(['African American  or Black', 'Caucasian or White'])].loc[:,'race'].index
AllSuperTable_2['race'].iloc[race_others_i] = 'Others'
AllSuperTable_2.race.unique()

/var/folders/fl/fpg3wpyx2kl9_skm4xg51z3h0000gn/T/ipykernel_30494/3242216070.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AllSuperTable_2['race'].iloc[race_others_i] = 'Others'

array(['African American  or Black', 'Caucasian or White', 'Others'],
      dtype=object)

In [10]:
AllSuperTable_2.reset_index(drop=True, inplace=True)
eth_others_i = AllSuperTable_2[~AllSuperTable_2.ethnicity.isin(['Non-Hispanic or Latino','Hispanic or Latino'])].loc[:,'ethnicity'].index
AllSuperTable_2['ethnicity'].iloc[eth_others_i] = 'Others'
AllSuperTable_2.ethnicity.unique()

/var/folders/fl/fpg3wpyx2kl9_skm4xg51z3h0000gn/T/ipykernel_30494/8533180.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AllSuperTable_2['ethnicity'].iloc[eth_others_i] = 'Others'

array(['Non-Hispanic or Latino', 'Others', 'Hispanic or Latino'],
      dtype=object)

In [11]:
print('Unique CSNs:',len(AllSuperTable_2.csn.unique()), len(AllSuperTable_2[AllSuperTable_2.BSF_group==1].csn.unique()),
      len(AllSuperTable_2[AllSuperTable_2.BSF_group==2].csn.unique()),len(AllSuperTable_2[AllSuperTable_2.BSF_group==3].csn.unique()),
     len(AllSuperTable_2[AllSuperTable_2.BSF_group==4].csn.unique())) 

print('Unique Patients:',len(AllSuperTable_2.pat_id.unique()), len(AllSuperTable_2[AllSuperTable_2.BSF_group==1].pat_id.unique()),
      len(AllSuperTable_2[AllSuperTable_2.BSF_group==2].pat_id.unique()),len(AllSuperTable_2[AllSuperTable_2.BSF_group==3].pat_id.unique()),
      len(AllSuperTable_2[AllSuperTable_2.BSF_group==4].pat_id.unique()))

Unique CSNs: 13274 1772 2306 2565 7938
Unique Patients: 11828 1754 2246 2475 7118

In [12]:
AllSuperTable_2.BSF_group.value_counts()

BSF_group
4    10795
3     3270
2     2724
1     1927
Name: count, dtype: int64

In [13]:
cols = ['age', 'gender','race','ethnicity', 'daily_weight_kg', 'height_cm',#'Tcount_7d',
        'hematocrit', 'hemoglobin',
        #'best_map','pulse',
        'blood_urea_nitrogen_(bun)','creatinine','platelets',# 'white_blood_cell_count',
        'bilirubin_total', #'fibrinogen', 
        'inr',#'partial_prothrombin_time_(ptt)',#'b-type_natriuretic_peptide_(bnp)',
        'fio2','pf_sp','pf_pa',
        'gcs_total_score','SOFA_max_hourly_total']


groupby = ['BSF_group']
cols = cols
categorical=['gender','race','ethnicity']

##### limit the binary variable to a single row
# limit = {"hispanic": 1}
labels={'BSF_group': 'Baseline SF groups'}
data = AllSuperTable_2.copy()
data_unimputed = TableOne(data, missing=False, columns=cols, categorical=categorical, groupby=groupby,rename=labels,label_suffix=True, pval=True, htest_name=True) #, nonnormal=nonnormal) #, limit=limit) 
#, columns=columns, categorical=categorical, groupby=groupby, nonnormal=nonnormal, rename=labels, pval=False)
data_unimputed



# data_unimputed.to_latex('DATA_RESULTS_REV1/tableoneEmory_unimputed_rev1.tex')
# data_unimputed.to_csv('DATA_RESULTS_REV1/tableoneEmory_unimputed_rev1.csv')

                                                                Grouped by Baseline SF groups
                                                                                      Overall              1              2              3              4 P-Value           Test
n                                                                                       18716           1927           2724           3270          10795
age, mean (SD)                                                                    61.4 (16.0)    62.0 (15.5)    60.7 (15.2)    61.2 (15.0)    61.5 (16.5)   0.030  One-way ANOVA
gender, n (%)                        Female                                       9708 (51.9)     956 (49.6)    1403 (51.5)    1665 (50.9)    5684 (52.7)   0.047    Chi-squared
                                     Male                                         9008 (48.1)     971 (50.4)    1321 (48.5)    1605 (49.1)    5111 (47.3)
race, n (%)                          African American  or Black                   8428 (45.0)     769 (39.9)    1002 (36.8)    1469 (44.9)    5188 (48.1)  <0.001    Chi-squared
                                     Caucasian or White                           8724 (46.6)     939 (48.7)    1455 (53.4)    1503 (46.0)    4827 (44.7)
                                     Others                                        1564 (8.4)     219 (11.4)      267 (9.8)      298 (9.1)      780 (7.2)
ethnicity, n (%)                     Hispanic or Latino                             574 (3.1)       58 (3.0)      105 (3.9)       95 (2.9)      316 (2.9)  <0.001    Chi-squared
                                     Non-Hispanic or Latino                      16801 (89.8)    1677 (87.0)    2402 (88.2)    2882 (88.1)    9840 (91.2)
                                     Others                                        1341 (7.2)     192 (10.0)      217 (8.0)      293 (9.0)      639 (5.9)
daily_weight_kg, mean (SD)                                                        81.8 (61.8)    82.6 (25.8)   87.9 (149.6)    87.3 (27.3)    78.5 (24.1)  <0.001  One-way ANOVA
height_cm, mean (SD)                                                             169.1 (13.0)   169.2 (14.4)   169.4 (13.1)   169.1 (12.1)   169.1 (12.9)   0.736  One-way ANOVA
hematocrit, mean (SD)                                                              24.5 (4.3)     27.0 (5.9)     26.2 (4.7)     24.3 (3.2)     23.7 (3.8)  <0.001  One-way ANOVA
hemoglobin, mean (SD)                                                               7.8 (1.4)      8.7 (2.0)      8.4 (1.6)      7.8 (1.1)      7.6 (1.2)  <0.001  One-way ANOVA
blood_urea_nitrogen_(bun), mean (SD)                                              33.7 (27.0)    32.4 (23.3)    33.0 (25.9)    35.8 (27.6)    33.4 (27.6)  <0.001  One-way ANOVA
creatinine, mean (SD)                                                               2.2 (2.6)      1.9 (2.1)      1.9 (2.1)      2.1 (2.3)      2.3 (2.9)  <0.001  One-way ANOVA
platelets, mean (SD)                                                            200.2 (139.8)  193.6 (132.2)  198.3 (134.3)  189.8 (132.9)  204.8 (144.2)  <0.001  One-way ANOVA
bilirubin_total, mean (SD)                                                          1.7 (4.1)      1.8 (4.6)      1.8 (4.0)      1.7 (3.8)      1.6 (4.1)   0.155  One-way ANOVA
inr, mean (SD)                                                                      1.5 (0.9)      1.5 (0.9)      1.5 (0.8)      1.4 (0.8)      1.5 (0.9)   0.005  One-way ANOVA
fio2, mean (SD)                                                                     0.4 (0.4)      0.6 (0.3)      0.5 (0.1)      0.4 (0.0)      0.3 (0.7)  <0.001  One-way ANOVA
pf_sp, mean (SD)                                                                 271.8 (99.4)   184.0 (81.6)   211.1 (54.3)   256.9 (28.2)   384.6 (75.8)  <0.001  One-way ANOVA
pf_pa, mean (SD)                                                                306.4 (143.2)  239.0 (143.7)  265.5 (127.2)  310.6 (125.1)  387.8 (137.2)  <0.001  One-way ANOVA
gcs_total_score, mean (SD)                                                         13.5 (2.9)     12.6 (3.9)     12.4 (3.7)     12.3 (3.4)     14.2 (1.9)  <0.001  One-way ANOVA
SOFA_max_hourly_total, mean (SD)                                                    4.6 (3.7)      6.6 (4.7)      6.4 (4.1)      6.0 (3.6)      3.4 (2.8)  <0.001  One-way ANOVA

# Grady data process

In [ ]:
dfGr_transf0 = pd.read_csv("DATA_RESULTS/df_GRADY_RBCT_extractedFeat_NoImputated_tau9_v3.csv")
dfGr_transf0.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
dfGr_transf0.drop_duplicates(inplace=True)

'''

Eliminated the patients having pre-transfusion SF, Hb, SpO2, PF missing

'''
print(dfGr_transf0[['med_spo2_beforeT', 'med_Hb_beforeT', 'med_SF_beforeT','med_PF_beforeT']].isnull().all(axis=1).sum())

dfGr_transf = dfGr_transf0[~dfGr_transf0[['med_spo2_beforeT', 'med_Hb_beforeT', 'med_SF_beforeT','med_PF_beforeT']].isnull().all(axis=1)]
dfGr_transf.reset_index(drop=True, inplace=True)
print(dfGr_transf.shape)

dfGr_transf

In [ ]:
### LOAD EMORY TRANSFUSION PHENOTYPING DATA
GrAllSuperTable_0 = pd.read_csv('../Transfusion_Phenotyping_Data_EmoryGrady/dfGrady_RBC_T_AllFeatures_NoOurlierRejected_NoImputed_v1g.csv')
GrAllSuperTable_0.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)
GrAllSuperTable_0

In [16]:
dfGr_transf.columns, GrAllSuperTable_0.columns, dfGr_transf['Hb'].isnull().sum(), GrAllSuperTable_0['SOFA_max_hourly_total'].isnull().sum()

(Index(['pat_id', 'csn', 'age_yrs', 'transfusion_start', 'transfusion_end',
        'blood_product_name', 'hospital_admission_date_time',
        'hospital_discharge_date_time', 'unit', 'year', 'Arb', 'Tcount_7d',
        'discharge_to', 'age', 'gender', 'race', 'ethnicity', 'Hb',
        'med_spo2_beforeT', 'med_Hb_beforeT', 'med_SF_beforeT',
        'med_PF_beforeT', 'MSPO2_afterT1', 'MSPO2_afterT2', 'MSPO2_afterT3',
        'MHB_afterT1', 'MHB_afterT2', 'MHB_afterT3', 'MSF_afterT1',
        'MSF_afterT2', 'MSF_afterT3', 'MPF_afterT1', 'MPF_afterT2',
        'MPF_afterT3', 'del_SPO2_1', 'del_SPO2_2', 'del_SPO2_3', 'del_Hb_1',
        'del_Hb_2', 'del_Hb_3', 'del_SF_1', 'del_SF_2', 'del_SF_3', 'del_PF_1',
        'del_PF_2', 'del_PF_3'],
       dtype='object'),
 Index(['pat_id', 'PAT_ID', 'csn', 'age_yrs', 'transfusion_start',
        'transfusion_end', 'blood_product_name', 'hospital_admission_date_time',
        'hospital_discharge_date_time', 'unit',
        ...
        'SOFA_max_hourly_total', 'norepinephrine_dose_unit_mcg/min',
        'epinephrine_dose_unit_mcg/min', 'phenylephrine_dose_unit_mcg/min',
        'vasopressin_dose_unit_Units/min', 'dobutamine_dose_unit_mcg/kg/min',
        'dopamine_dose_unit_mcg/kg/min', 'vasopressin_dose_unit_Units/hr',
        'vasopressin_dose_unit_Units', 'pf_sa'],
       dtype='object', length=106),
 0,
 0)

In [ ]:
GrAllSuperTable_1 = dfGr_transf.merge(GrAllSuperTable_0, how='left', on=['pat_id', 'csn', 'age_yrs', 'transfusion_start', 'transfusion_end',
        'blood_product_name', 'hospital_admission_date_time',
        'hospital_discharge_date_time', 'unit', 'year', 'Arb', 'Tcount_7d',
        'discharge_to', 'age', 'gender', 'race', 'ethnicity'])
print(GrAllSuperTable_1['SOFA_max_hourly_total'].isnull().sum())
GrAllSuperTable_1

In [18]:
GrAllSuperTable_2 = GrAllSuperTable_1[~GrAllSuperTable_1['med_SF_beforeT'].isnull()]
GrAllSuperTable_2.reset_index(drop=True, inplace=True)

del cond1, cond2, cond3, cond4, C1, C2, C3, C4
Grbsf = GrAllSuperTable_2['med_SF_beforeT']
cond1 = (Grbsf>0) & (Grbsf<=143)
cond2 = (Grbsf>143) & (Grbsf<=235)
cond3 = (Grbsf>235) & (Grbsf<=315)
cond4 = (Grbsf>315) 

C1 = pd.Series(cond1, dtype=int)*1
C2 = pd.Series(cond2, dtype=int)*2
C3 = pd.Series(cond3, dtype=int)*3
C4 = pd.Series(cond4, dtype=int)*4
GrAllSuperTable_2['BSF_group'] = C1 + C2 + C3 + C4

In [19]:
GrAllSuperTable_2.race.unique(), GrAllSuperTable_2.ethnicity.unique()

(array(['Black or African American', 'White or Caucasian', 'Hispanic',
        'Asian', 'Other', 'Unknown',
        'Native Hawaiian and Other Pacific Islander', 'Multi-Racial',
        'American Indian and Alaskan Native'], dtype=object),
 array(['Non-Hispanic', 'Hispanic', 'Unknown'], dtype=object))

In [20]:
GrAllSuperTable_2.reset_index(drop=True, inplace=True)
race_others_i = GrAllSuperTable_2[~GrAllSuperTable_2.race.isin(['Black or African American', 'White or Caucasian'])].loc[:,'race'].index
GrAllSuperTable_2['race'].iloc[race_others_i] = 'Others'
GrAllSuperTable_2.race.unique()

/var/folders/fl/fpg3wpyx2kl9_skm4xg51z3h0000gn/T/ipykernel_30494/223393167.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GrAllSuperTable_2['race'].iloc[race_others_i] = 'Others'

array(['Black or African American', 'White or Caucasian', 'Others'],
      dtype=object)

In [21]:
GrAllSuperTable_2.reset_index(drop=True, inplace=True)
eth_others_i = GrAllSuperTable_2[~GrAllSuperTable_2.ethnicity.isin(['Non-Hispanic', 'Hispanic'])].loc[:,'ethnicity'].index
GrAllSuperTable_2['ethnicity'].iloc[eth_others_i] = 'Others'
GrAllSuperTable_2.ethnicity.unique()

/var/folders/fl/fpg3wpyx2kl9_skm4xg51z3h0000gn/T/ipykernel_30494/1910014470.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  GrAllSuperTable_2['ethnicity'].iloc[eth_others_i] = 'Others'

array(['Non-Hispanic', 'Hispanic', 'Others'], dtype=object)

In [22]:
print('Unique CSNs:',len(GrAllSuperTable_2.csn.unique()), len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==1].csn.unique()),
      len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==2].csn.unique()),len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==3].csn.unique()),
     len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==4].csn.unique())) 

print('Unique Patients:',len(GrAllSuperTable_2.pat_id.unique()), len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==1].pat_id.unique()),
      len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==2].pat_id.unique()),len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==3].pat_id.unique()),
      len(GrAllSuperTable_2[GrAllSuperTable_2.BSF_group==4].pat_id.unique()))

Unique CSNs: 3757 622 659 1798 1554
Unique Patients: 3552 618 654 1748 1489

In [25]:
cols = ['age', 'gender','race','ethnicity', 'daily_weight_kg', 'height_cm',#'Tcount_7d',
        'hematocrit', 'hemoglobin',
        #'best_map','pulse',
        'blood_urea_nitrogen_(bun)','creatinine','platelets',# 'white_blood_cell_count',
        'bilirubin_total', #'fibrinogen', 
        'inr',#'partial_prothrombin_time_(ptt)',#'b-type_natriuretic_peptide_(bnp)',
        'fio2','pf_sp','pf_pa',
        'gcs_total_score','SOFA_max_hourly_total']


from tableone import TableOne
groupby = ['BSF_group']
cols = cols
categorical=['gender','race','ethnicity']

##### limit the binary variable to a single row
# limit = {"hispanic": 1}
labels={'BSF_group': 'Baseline SF groups'}
Grdata = GrAllSuperTable_2.copy()
Grdata_unimputed = TableOne(Grdata, missing=False, columns=cols, categorical=categorical, groupby=groupby,rename=labels,label_suffix=True, pval=True, htest_name=False) #, nonnormal=nonnormal) #, limit=limit) 
#, columns=columns, categorical=categorical, groupby=groupby, nonnormal=nonnormal, rename=labels, pval=False)
Grdata_unimputed

# Grdata_unimputed.to_latex('DATA_RESULTS_REV1/tableoneGrady_unimputed_rev1.tex')
# Grdata_unimputed.to_csv('DATA_RESULTS_REV1/tableoneGrady_unimputed_rev1.csv')

                                                               Grouped by Baseline SF groups
                                                                                     Overall              1              2              3              4 P-Value
n                                                                                       6375            689            817           2787           2082
age, mean (SD)                                                                   53.7 (17.5)    53.8 (17.3)    55.3 (16.9)    53.5 (17.3)    53.2 (17.9)   0.037
gender, n (%)                        Female                                      2634 (41.3)     266 (38.6)     313 (38.3)    1136 (40.8)     919 (44.1)   0.006
                                     Male                                        3741 (58.7)     423 (61.4)     504 (61.7)    1651 (59.2)    1163 (55.9)
race, n (%)                          Black or African American                   4751 (74.5)     497 (72.1)     533 (65.2)    2094 (75.1)    1627 (78.1)  <0.001
                                     Others                                        498 (7.8)       51 (7.4)       78 (9.5)      217 (7.8)      152 (7.3)
                                     White or Caucasian                          1126 (17.7)     141 (20.5)     206 (25.2)     476 (17.1)     303 (14.6)
ethnicity, n (%)                     Hispanic                                      279 (4.4)       23 (3.3)       40 (4.9)      127 (4.6)       89 (4.3)   0.682
                                     Non-Hispanic                                6043 (94.8)     662 (96.1)     768 (94.0)    2638 (94.7)    1975 (94.9)
                                     Others                                         53 (0.8)        4 (0.6)        9 (1.1)       22 (0.8)       18 (0.9)
daily_weight_kg, mean (SD)                                                       81.0 (25.8)    82.9 (25.0)    84.7 (26.2)    82.1 (27.8)    77.4 (22.5)  <0.001
height_cm, mean (SD)                                                            171.7 (11.5)   172.0 (10.9)   172.1 (13.6)   171.8 (11.2)   171.2 (11.3)   0.133
hematocrit, mean (SD)                                                             24.0 (5.2)     26.3 (7.0)     25.1 (5.7)     23.5 (4.2)     23.4 (5.2)  <0.001
hemoglobin, mean (SD)                                                              8.0 (1.8)      8.7 (2.4)      8.5 (1.9)      7.8 (1.5)      7.8 (1.8)  <0.001
blood_urea_nitrogen_(bun), mean (SD)                                             31.9 (27.9)    35.8 (30.6)    34.9 (26.0)    32.8 (26.9)    28.2 (28.7)  <0.001
creatinine, mean (SD)                                                              2.0 (2.6)      2.3 (2.7)      2.0 (2.2)      1.9 (2.1)      2.1 (3.1)   0.009
platelets, mean (SD)                                                           225.0 (148.8)  213.5 (135.6)  210.7 (139.0)  222.6 (150.4)  238.1 (153.7)  <0.001
bilirubin_total, mean (SD)                                                         1.3 (2.6)      1.7 (3.5)      1.5 (2.9)      1.2 (2.4)      1.1 (2.4)  <0.001
inr, mean (SD)                                                                     1.4 (0.8)      1.4 (0.9)      1.4 (0.9)      1.3 (0.6)      1.3 (0.9)   0.014
fio2, mean (SD)                                                                    0.4 (0.2)      0.7 (0.3)      0.5 (0.1)      0.4 (0.1)      0.3 (0.1)  <0.001
pf_sp, mean (SD)                                                                251.8 (79.9)   163.8 (75.1)   198.5 (35.7)   266.4 (56.1)   352.9 (67.4)  <0.001
pf_pa, mean (SD)                                                               302.2 (123.8)  237.7 (123.1)  254.6 (102.1)  323.3 (112.8)  361.9 (147.4)  <0.001
gcs_total_score, mean (SD)                                                        11.9 (3.8)     10.5 (4.7)      9.8 (3.8)     11.0 (3.8)     14.2 (1.9)  <0.001
SOFA_max_hourly_total, mean (SD)                                                   5.3 (3.9)      8.0 (4.5)      8.1 (3.9)      5.6 (3.5)      2.9 (2.5)  <0.001